### ISSUE TITLE
1 second additional countdown?

### ISSUE THREAD

**Issue by husnulhamidiah** [mrchimp/tock#27] opened 2015-07-02 10:23 UTC
I try to make a simple countdown. But later I notice that complete callback run a second after the countdown reach 0. Is there any solution or may be I did it wrong?

**Comment by mrchimp** [comment] 2015-07-02 16:48
Maybe. Post your code here?

**Comment by mrchimp** [comment] 2015-09-19 19:59
I can't reproduce this so I'm going to close the issue. If you post some code, I'll re-open it and take a look.

**Closed by mrchimp** 2015-09-19 19:59 UTC
